version: '3'
services:
  web:
    image: flaskapp:latest
    build: .
    restart: "no"
    ports:
      - "5000:5000"
    volumes:
      - /home/ubuntu/proyek-stupen/tugas-web-kak-alfan/templates:/app/templates  # Mount the templates folder
      - /home/ubuntu/proyek-stupen/tugas-web-kak-alfan/app.py:/app/app.py        # Mount app.py
