name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          echo "${{ secrets.UBUNTU_INSTANCE_EC2 }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add EC2 host to known_hosts
        run: |
          ssh-keyscan -H 3.223.49.50 >> ~/.ssh/known_hosts

      - name: Pull latest code and restart Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 ubuntu@3.223.49.50 "cd /home/ubuntu/proyek-stupen/tugas-web-kak-alfan && git pull origin main"
