name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Sesuaikan dengan branch yang kamu gunakan

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.1
      with:
        ssh-private-key: ${{ secrets.UBUNTU_INSTANCE_EC2 }}

    - name: Pull the latest changes from GitHub
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.223.49.50 "cd /home/ubuntu/proyek-stupen/tugas-web-kak-alfan && git pull origin main"
